baseURL = "https://casahugo.github.io/blog/"
languageCode = "fr-fr"
title = "Hugo Casabella"
theme = "resume-hugo"
publishDir = "docs"

[params]
    firstName = "Hugo"
    lastName = "Casabella"
    address = "Lyon, France"
    contactNote = "Développeur Back-End passionné | PHP Symfony | Go | SQL | DDD | Clean Architecture | DevOps"
    profileImage = "img/me2.jpeg"
    email = "hugo.casabella@gmail.com"
    description = """
Fort d’une expertise en PHP (Symfony), ReactJs et Golang, je conçois et maintiens des applications performantes et évolutives, avec un fort accent sur la qualité logicielle et l'optimisation.

Mon approche repose sur des principes solides :
- Domain-Driven Design (DDD) pour une modélisation métier efficace.
- Clean Architecture pour des applications robustes et maintenables.
- Modernisation & Migration de legacy : refonte progressive, amélioration continue et transition vers des architectures modernes.
- DevOps & CI/CD : automatisation des processus d’intégration et de déploiement pour plus d’efficacité et de rapidité.
 """
    description2 = "Toujours à la recherche de nouveaux défis, je suis animé par l’envie de concevoir des solutions techniques innovantes et de partager mes connaissances avec les équipes."
    description3 = "Échangeons ! Je serais ravi de discuter de vos projets et de voir comment nous pourrions collaborer."
    favicon = "images/favicon.ico"

    # what sections to display.  Setting to false disables navigation and section.
    showSkills = true
    showProjects = false
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = false
    showQr = false

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/hugo-casabella-15b01a163/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/casahugo"

#[params.google.analytics]
#    trackerID = "XX-123446-01"

[outputs] #only required for search
    home = ["HTML", "JSON"]